### ISSUE TITLE
Problem with security group and subnet configuration

### ISSUE THREAD

**Issue by janeczku** [Huawei/DockerMachineDriver4OTC#1]
1. There should be an error when the security group specified by the user can not be found. But the driver does not error:

https://github.com/Huawei/DockerMachineDriver4OTC/blob/master/otc/ecs.go#L724

2. When there are more than 10 security groups in the VPC, then setting the security group may fail. Because the driver implementation does only query the first 10 security groups for the VPC. It does not support the paged API response.

https://github.com/Huawei/DockerMachineDriver4OTC/blob/master/otc/ecs.go#L715

3. Same problem with subnet. Driver only queries first 10 subnets in the VPC:

https://github.com/Huawei/DockerMachineDriver4OTC/blob/master/otc/ecs.go#L646

**Comment by x1022as** [comment]
10 limit can be reset here: https://github.com/Huawei/DockerMachineDriver4OTC/blob/master/otc/ecs.go#L38

set to 0 means intmax, see https://github.com/Huawei/DockerMachineDriver4OTC/blob/master/com/client/vpcClient.go#L332

**Comment by zzhaoy** [comment]
The issue has been fixed by PR #2, please check
