### ISSUE TITLE
otc-private-address-only config parameter is not implemented

### ISSUE THREAD

**Issue by janeczku** [Huawei/DockerMachineDriver4OTC#14]
The README documents a parameter to create a ECS without an Elastic IP (`--otc-private-address-only`) but this configuration option is not implemented in the driver.

**Comment by hvpareja** [comment]
@zzhaoy 

So the fix was to remove it from the documentation instead of implement it? How are we supposed to create machines with no elastic ip? Also, I find it an inconvenient the fact that docker-machine tries to ssh over the elastic ip by default.
