### ISSUE TITLE
Failed to crate ssh key pair: unknown error

### ISSUE THREAD

**Issue by beevelop** [Huawei/DockerMachineDriver4OTC#24]
Trying to spin up an ECS instance on the OTC, I stumbled upon the following issue:
```
Error creating machine: Error in driver during machine creation: otc04 | Failed to crate ssh key pair: unknown error, status code: 400, err: { }
```

There is no further information provided and no sane way to debug it. The command used is nearly identical to the example provided in the README.

**Comment by x1022as** [comment]
@beevelop could you provide some more detailed procedure to reproduce, like command-line arguments? Tks.

**Comment by AdamVB** [comment]
I'm facing the same issue, command to reproduce:

docker-machine create -d otc --otc-service-endpoint=https://ecs.eu-de.otc.t-systems.com --otc-access-key-id=XXXXXXXX --otc-access-key-secret=XXXXXXXXXXX --otc-security-group=gitlab-runners --otc-tenant-id=XXXXXXXXXX --otc-region=eu-de --otc-vpc-id=XXXXX-XXXX-XXXX-XXXX-XXXX	 --otc-flavor-id=s2.large.2 --otc-image-id=Standard_Ubuntu_18.04_latest --otc-subnet-id=XXXXXXX --otc-available-zone=eu-de-01 docker-machine-test

**Comment by beevelop** [comment]
I figured out, that the error itself was not related to the SSH key pair at all. It wasn't able to find the respective project. You can get a lot of what is really happening through the `--debug` flag.

**Comment by AdamVB** [comment]
Thanks a lot. Tenant-ID = Project ID

**Comment by beevelop** [comment]
This is something, that should be stated in the README.

**Comment by tischrei** [comment]
This will be stated in the README with the pull requested initiated by
https://github.com/Huawei/DockerMachineDriver4OTC/pull/26

Would be cool, to close this issue keeping the issue tracker clear ;-).
