### ISSUE TITLE
Add support for user-data

### ISSUE THREAD

**Issue by tischrei** [Huawei/DockerMachineDriver4OTC#27]
Running docker-machine on CentOS fails due to missing open port because of firewalld. firewalld needs to be stopped or better reconfigured while machine creation: 

`sudo firewall-cmd --add-port=2376/tcp`

Is there any way to solve this?

**Comment by x1022as** [comment]
`2376` is management port for docker/docker-machine, should be set properly during docker-related tools installing.

DockerMachinDriver4OTC is just docker-machine plugin for OTC platform, it's not qualified to do this

**Comment by tischrei** [comment]
How can this done properly while machine creation?

**Comment by x1022as** [comment]
`sudo firewall-cmd --add-port=2376/tcp`  is not  the right solution?

**Comment by tischrei** [comment]
Of course, this can be done, if you connect seperatly to the CentOS host and run this command. But I am more looking for some kind of solution to avoid this situation and to run environments like Rancher where you don't touch the remote host in any way.

Some kind of solution would be better to pass this config to the desired host via user data or something like this.

**Comment by x1022as** [comment]
Not sure if I get your point right.

I'd say that this port should be set open when docker environment (on each host) were installed, It's like some running dependency of docker/docker-machine, so maybe it should be set in some docker-install scripts if exist.

**Comment by tischrei** [comment]
But this is not the best solution. Because the installation will be done automatically the last docker version and so the user has to maintain the script, too. Why you don't integrate the user-data field which makes much more sense and is 100% cloud like?

**Comment by tischrei** [comment]
**UPDATE**
I changed the titel to make clear that user-data should be supported to solve such issues and to enable other customizations.

**Comment by x1022as** [comment]
~~DockerMachineDriver4OTC is just a **plugin** of docker-machine~~

should  take aws machine driver (`https://github.com/docker/docker.github.io/blob/master/machine/drivers/aws.md#security-group`) as a reference
