### ISSUE TITLE
Hung on when create ECS

### ISSUE THREAD

**Issue by Cusfomer-kubectl** [Huawei/DockerMachineDriver4OTC#3]
The description of users' problem:
 I got the compile environment working a few days ago and was testing to get the driver running, but it doesn't work properly. It always hangs after creating ssh key in OTC.

**Comment by x1022as** [comment]
```
(tino-new-sg-rancher-2) tino-new-sg-rancher-2 | Configuring subnet for instance ...
(tino-new-sg-rancher-2) tino-new-sg-rancher-2 | Create SSH key pair ...
(tino-new-sg-rancher-2) tino-new-sg-rancher-2 | Issuing request to create instance ...
```
creating ssh key pair has done successfully, it's waiting for createInstance():
```
        log.Infof("%s | Create SSH key pair ...", d.MachineName)
        if err := d.instanceKeyPairCreate(); err != nil {
                return fmt.Errorf("%s | Failed to crate ssh key pair: %v", d.MachineName, err)
        }   

        log.Infof("%s | Issuing request to create instance ...", d.MachineName)
        createResp, err := d.createInstance()
        if err != nil {
                return fmt.Errorf("%s | Failed to crate instance: %v", d.MachineName, err)
        }
```
walking through createInstance(), I didn't find any blocking code, which is weird. if succeed, it would have these lines in log:
```
request body:
request: xxxxx
``` 
So I suggest to add some log in createInstance(), recompile and run, to locate the blocking part.

**Comment by x1022as** [comment]
can any one test this with `debug` log-level, it seems to be `info` now.

**Comment by zzhaoy** [comment]
From Heiko Reinhardt, T-Systems International GmbH:

```
Hi Youg,

I’ve noticed that the problem with the docker-machine driver could be a problem with the OTC access key.
I’ve an old access key, I’ve created 18.1.2017 which is working without problems.
And I have one I’ve created 6.3.2017 which is not working.
I’ve droped this key and recreated a new one and the new one is also working.
To access the API with the wrong key to get all information about the tenant was no problem.

Could this help?
```

**Comment by abussjae** [comment]
This patch fixed hangs while using otc machine driver:

(robot.venv)linux@qa-host03:~/go/docker/src/github.com/huawei/DockerMachineDriver4OTC$ diff -c otc/ecs.go.bak otc/ecs.go
*** otc/ecs.go.bak      Thu Jun 22 06:39:25 2017
--- otc/ecs.go  Thu Jun 22 10:08:31 2017
***************
*** 669,675 ****
        //listImgsReq.SetLimit(imgListNumPerPage)

        imagesList := pClient.ListCloudImages(listImgsReq)
!       log.Debugf("%v", imagesList.Images)

        for _, image := range imagesList.Images {
                if imageId == image.Id {
--- 669,675 ----
        //listImgsReq.SetLimit(imgListNumPerPage)

        imagesList := pClient.ListCloudImages(listImgsReq)
!       // buggy log.Debugf("%v", imagesList.Images)

        for _, image := range imagesList.Images {
                if imageId == image.Id {
